/**
 * Vendor the web fonts into public/fonts + generate src/styles/fonts.css.
 *
 * Self-hosted rather than <link>ed so the site has no third-party runtime
 * dependency: it keeps working on an offline/intranet deploy, avoids the
 * privacy and consent questions that come with a font CDN, and removes a
 * render-blocking cross-origin round trip.
 *
 * Run once; the output is committed. `npm run fonts` to refresh.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(HERE, '..', 'public', 'fonts');
const CSS_OUT = join(HERE, '..', 'src', 'styles', 'fonts.css');

// A modern UA is required or Google serves .ttf instead of .woff2.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/** Only these subsets ship — cyrillic/greek/vietnamese would be dead weight. */
const KEEP = new Set(['latin', 'latin-ext', 'arabic', 'bengali']);

const FAMILIES = [
  // Primary. Variable, and covers Arabic *and* Latin — one family for both scripts.
  { name: 'Fustat', spec: 'Fustat:wght@200..800' },
  // Secondary Arabic: heavier, more editorial than Fustat for headings.
  { name: 'Almarai', spec: 'Almarai:wght@300;400;700;800' },
  // Latin UI.
  { name: 'Poppins', spec: 'Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400' },
  { name: 'Ubuntu', spec: 'Ubuntu:ital,wght@0,400;0,500;0,700;1,400' },
  // The ayah itself — the same face the rendered video uses.
  { name: 'Aref Ruqaa', spec: 'Aref+Ruqaa:wght@400;700' },
  // Bengali UI (the `bn` locale).
  { name: 'Noto Sans Bengali', spec: 'Noto+Sans+Bengali:wght@400;600;700' },
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-');

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const blocks = [];
  let downloaded = 0;

  for (const fam of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${fam.spec}&display=swap`;
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${fam.name}: css ${res.status}`);
    const css = await res.text();

    // Each @font-face is preceded by a `/* subset */` comment.
    const chunks = css.split(/\/\*\s*([a-z-]+)\s*\*\//i).slice(1);
    for (let i = 0; i < chunks.length; i += 2) {
      const subset = chunks[i];
      let face = chunks[i + 1];
      if (!KEEP.has(subset) || !face?.includes('@font-face')) continue;

      const m = face.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/);
      if (!m) continue;

      const weight = (face.match(/font-weight:\s*([^;]+);/) ?? [])[1]?.trim().replace(/\s+/g, '-') ?? '400';
      const italic = /font-style:\s*italic/.test(face);
      const file = `${slug(fam.name)}-${subset}-${weight}${italic ? '-italic' : ''}.woff2`;

      const bin = await fetch(m[1], { headers: { 'User-Agent': UA } });
      if (!bin.ok) throw new Error(`${file}: ${bin.status}`);
      await writeFile(join(OUT_DIR, file), Buffer.from(await bin.arrayBuffer()));
      downloaded++;

      blocks.push(face.replace(m[0], `url('/fonts/${file}')`).trim());
    }
  }

  const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n`;
  await writeFile(CSS_OUT, header + blocks.join('\n\n') + '\n');
  console.log(`${downloaded} font files → public/fonts, ${blocks.length} @font-face rules → src/styles/fonts.css`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
